# Explore here

In [1]:
# Your code here

import pandas as pd

df = pd.read_csv('https://breathecode.herokuapp.com/asset/internal-link?id=733&path=demographic_health_data.csv')
df

,fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,...,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code
0,1001,55601,6787,12.206615,7637,13.735364,6878,12.370281,7089,12.749771,...,3644,12.9,11.9,13.8,5462,3.1,2.9,3.3,1326,3
1,1003,218022,24757,11.355276,26913,12.344167,23579,10.814964,25213,11.564429,...,14692,12.0,11.0,13.1,20520,3.2,3.0,3.5,5479,4
2,1005,24881,2732,10.980266,2960,11.896628,3268,13.134520,3201,12.865239,...,2373,19.7,18.6,20.6,3870,4.5,4.2,4.8,887,6
3,1007,22400,2456,10.964286,2596,11.589286,3029,13.522321,3113,13.897321,...,1789,14.1,13.2,14.9,2511,3.3,3.1,3.6,595,2
4,1009,57840,7095,12.266598,7570,13.087828,6742,11.656293,6884,11.901798,...,4661,13.5,12.6,14.5,6017,3.4,3.2,3.7,1507,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3135,56037,43051,6104,14.178532,6326,14.694200,5359,12.448027,6577,15.277229,...,2098,8.9,8.3,9.6,2834,2.6,2.4,2.8,821,5
3136,56039,23081,2384,10.328842,2185,9.466661,2967,12.854729,4093,17.733200,...,928,7.2,6.5,8.0,1360,2.4,2.2,2.6,447,5
3137,56041,20299,3121,15.375142,3205,15.788955,2153,10.606434,2702,13.311001,...,1163,10.4,9.5,11.2,1500,3.0,2.8,3.2,430,5
3138,56043,7885,858,10.881420,1113,14.115409,715,9.067850,903,11.452124,...,506,11.3,10.3,12.1,686,3.4,3.2,3.7,207,6
3139,56045,6967,780,11.195637,779,11.181283,681,9.774652,906,13.004162,...,480,11.7,10.7,12.7,644,3.4,3.1,3.6,185,6

In [2]:
print(df.columns.tolist())

['fips', 'TOT_POP', '0-9', '0-9 y/o % of total pop', '19-Oct', '10-19 y/o % of total pop', '20-29', '20-29 y/o % of total pop', '30-39', '30-39 y/o % of total pop', '40-49', '40-49 y/o % of total pop', '50-59', '50-59 y/o % of total pop', '60-69', '60-69 y/o % of total pop', '70-79', '70-79 y/o % of total pop', '80+', '80+ y/o % of total pop', 'White-alone pop', '% White-alone', 'Black-alone pop', '% Black-alone', 'Native American/American Indian-alone pop', '% NA/AI-alone', 'Asian-alone pop', '% Asian-alone', 'Hawaiian/Pacific Islander-alone pop', '% Hawaiian/PI-alone', 'Two or more races pop', '% Two or more races', 'POP_ESTIMATE_2018', 'N_POP_CHG_2018', 'GQ_ESTIMATES_2018', 'R_birth_2018', 'R_death_2018', 'R_NATURAL_INC_2018', 'R_INTERNATIONAL_MIG_2018', 'R_DOMESTIC_MIG_2018', 'R_NET_MIG_2018', 'Less than a high school diploma 2014-18', 'High school diploma only 2014-18', "Some college or associate's degree 2014-18", "Bachelor's degree or higher 2014-18", 'Percent of adults with less than a high school diploma 2014-18', 'Percent of adults with a high school diploma only 2014-18', "Percent of adults completing some college or associate's degree 2014-18", "Percent of adults with a bachelor's degree or higher 2014-18", 'POVALL_2018', 'PCTPOVALL_2018', 'PCTPOV017_2018', 'PCTPOV517_2018', 'MEDHHINC_2018', 'CI90LBINC_2018', 'CI90UBINC_2018', 'Civilian_labor_force_2018', 'Employed_2018', 'Unemployed_2018', 'Unemployment_rate_2018', 'Median_Household_Income_2018', 'Med_HH_Income_Percent_of_State_Total_2018', 'Active Physicians per 100000 Population 2018 (AAMC)', 'Total Active Patient Care Physicians per 100000 Population 2018 (AAMC)', 'Active Primary Care Physicians per 100000 Population 2018 (AAMC)', 'Active Patient Care Primary Care Physicians per 100000 Population 2018 (AAMC)', 'Active General Surgeons per 100000 Population 2018 (AAMC)', 'Active Patient Care General Surgeons per 100000 Population 2018 (AAMC)', 'Total nurse practitioners (2019)', 'Total physician assistants (2019)', 'Total Hospitals (2019)', 'Internal Medicine Primary Care (2019)', 'Family Medicine/General Practice Primary Care (2019)', 'Total Specialist Physicians (2019)', 'ICU Beds_x', 'Total Population', 'Population Aged 60+', 'Percent of Population Aged 60+', 'COUNTY_NAME', 'STATE_NAME', 'STATE_FIPS', 'CNTY_FIPS', 'county_pop2018_18 and older', 'anycondition_prevalence', 'anycondition_Lower 95% CI', 'anycondition_Upper 95% CI', 'anycondition_number', 'Obesity_prevalence', 'Obesity_Lower 95% CI', 'Obesity_Upper 95% CI', 'Obesity_number', 'Heart disease_prevalence', 'Heart disease_Lower 95% CI', 'Heart disease_Upper 95% CI', 'Heart disease_number', 'COPD_prevalence', 'COPD_Lower 95% CI', 'COPD_Upper 95% CI', 'COPD_number', 'diabetes_prevalence', 'diabetes_Lower 95% CI', 'diabetes_Upper 95% CI', 'diabetes_number', 'CKD_prevalence', 'CKD_Lower 95% CI', 'CKD_Upper 95% CI', 'CKD_number', 'Urban_rural_code']

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3140 entries, 0 to 3139
Columns: 108 entries, fips to Urban_rural_code
dtypes: float64(61), int64(45), str(2)
memory usage: 2.6 MB

In [4]:
# Encontrar cuales variables son str
df_texto = df.select_dtypes(include=['object', 'string'])
df_texto.head()

  COUNTY_NAME STATE_NAME
0     Autauga    Alabama
1     Baldwin    Alabama
2     Barbour    Alabama
3        Bibb    Alabama
4      Blount    Alabama

In [5]:
# Convierto las str a numemricas

df['COUNTY_NAME'] = pd.factorize(df['COUNTY_NAME'])[0]
df['STATE_NAME'] = pd.factorize(df['STATE_NAME'])[0]

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3140 entries, 0 to 3139
Columns: 108 entries, fips to Urban_rural_code
dtypes: float64(61), int64(47)
memory usage: 2.6 MB

# modelo

Pirmero correremos el modelos, ya que Lasso lleva la pendiente a cero de las variables que no tienen correlacion, lo que me permite descartar gran cantidad de ellas.

In [6]:
# Normalizamos

from sklearn.preprocessing import StandardScaler

scaler_norm = StandardScaler()
df_norm = pd.DataFrame(scaler_norm.fit_transform(df),index = df.index,columns= df.columns)

In [7]:
from sklearn.model_selection import train_test_split

x = df_norm.drop('Obesity_number',axis = 1)
y = df_norm['Obesity_number']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
# Corremos el modelo

from sklearn.linear_model import Lasso

lasso_model = Lasso(alpha=0.1,max_iter= 1000)

lasso_model.fit(x_train,y_train)
y_pred = lasso_model.predict(x_test)
y_pred

array([-2.74800418e-01,  4.74519315e-01, -2.27168804e-01,  3.38642649e-02,
        2.48407130e-01, -2.26607924e-01, -2.69029515e-01, -2.48042893e-01,
       -2.89411150e-01, -2.64603526e-01, -2.39700223e-01, -2.97818177e-01,
       -1.69971325e-02, -2.44057024e-01,  1.98460740e-01, -1.76291819e-01,
        2.83185210e+00, -2.46303108e-01, -2.01035624e-01, -2.88111905e-01,
       -2.22761723e-01, -2.71696150e-01, -2.64000746e-01, -2.78998846e-01,
        6.12348819e+00, -1.51160996e-01, -2.67520749e-01, -2.05059666e-01,
       -2.63502133e-01, -2.95602226e-01, -2.54038530e-01, -1.98497265e-01,
       -1.89972145e-01, -1.56797105e-01,  1.18403564e-01, -2.31434174e-01,
       -1.78759027e-01, -2.48322590e-01, -2.57028709e-01, -1.97212807e-01,
       -2.34825917e-01,  3.31209252e-01, -2.88699519e-01, -2.99727894e-01,
       -1.49594647e-01, -2.73382910e-01, -2.90127899e-01,  2.25035507e-02,
       -2.61897077e-01, -2.74661891e-01,  4.29477052e-01, -2.93813192e-01,
       -2.31356002e-01, -2.80590570e-01,  1.88308893e-01, -2.63431540e-01,
        1.52508412e+00, -2.04255717e-01, -1.33775541e-01, -2.65395114e-01,
        1.01214022e-01, -2.96530430e-01, -2.81578986e-01,  2.07548532e-01,
       -2.28572435e-01, -1.32433045e-01, -2.67656083e-01, -2.21205847e-01,
       -2.88662752e-01,  8.67112527e-01, -1.99904043e-01, -2.38623914e-01,
       -2.19862746e-01, -2.22019407e-01, -2.21178487e-01, -1.23398538e-01,
        8.64582377e-01, -2.35506032e-01, -2.89906344e-01, -2.79150394e-01,
       -2.24319854e-01, -3.96410900e-02,  2.22225831e-01, -3.04329444e-01,
       -2.82816440e-01, -2.74485007e-01,  2.12218365e+00, -2.48877555e-01,
       -2.03910565e-01,  2.14850778e-01, -2.66137040e-01, -2.95381793e-01,
       -2.59335900e-01, -1.98420944e-01, -2.59730417e-01, -2.21483466e-01,
       -2.30034306e-01, -2.74946142e-01,  3.15667738e-01, -3.03508125e-01,
        1.67791634e+00,  1.91176817e-01, -2.01221917e-01, -2.98167459e-01,
       -2.92115921e-01, -1.60335996e-01, -1.50390263e-01, -1.70571821e-01,
        1.70668501e-01,  5.23881781e-01, -3.03844952e-01,  1.07287537e-01,
        5.47944290e-01, -6.45130080e-02, -2.71369257e-01,  2.46043022e+00,
       -2.62594566e-01, -2.87270432e-01,  1.34277403e-01, -2.08641188e-01,
       -2.66052191e-01, -2.16541292e-01, -2.67985784e-01, -1.31039505e-01,
       -2.33730222e-01, -2.30431874e-01, -8.89290470e-02, -1.90818217e-01,
        2.72011578e-01, -9.28609318e-02, -2.72374503e-01, -2.95930308e-01,
       -1.29144373e-01, -3.03193582e-01, -1.24405037e-01, -2.03848731e-01,
       -2.51107890e-01,  6.59474023e-01, -1.16105740e-01, -2.58602804e-01,
       -2.06758024e-01, -2.60946351e-01,  2.40567781e+00, -2.29603576e-01,
       -2.85241123e-01, -2.74506292e-01, -2.31345701e-01, -2.99449371e-01,
       -4.34042888e-02, -2.58382746e-01, -2.58304308e-01,  3.45260578e+00,
       -2.38518664e-01, -1.25181641e-01, -2.78676949e-01, -2.58863062e-01,
       -2.98260144e-01, -2.72286192e-01,  9.11398332e-02, -2.76461689e-01,
       -2.26085371e-01, -2.44465687e-01, -2.69597054e-01, -2.96572114e-01,
       -2.13037807e-01, -1.23802394e-01, -2.29472123e-01,  6.57713639e-02,
        3.65785431e-01, -2.67537727e-01, -1.94536306e-01,  2.46708960e-01,
       -2.71882265e-01, -2.50582631e-01, -5.25626523e-02, -2.24413146e-01,
       -1.56204394e-01, -2.37287308e-02, -1.20828671e-01, -2.23792266e-01,
       -2.14894587e-01, -2.57567046e-01, -2.76228320e-01, -2.29343174e-01,
       -2.77391760e-01, -2.90032731e-01, -2.42175576e-01, -1.38902075e-01,
       -1.86924327e-01, -2.46418129e-01,  4.42040288e-02, -2.73773731e-01,
       -2.51600185e-01, -2.88633003e-01, -1.96514483e-01, -2.86217238e-01,
       -2.76977586e-01, -1.50276988e-01, -2.61550709e-01, -2.92719739e-01,
        4.03864876e-01,  7.29729829e-02,  3.52039552e+00, -2.53831011e-01,
       -6.59962253e-02, -2.59541908e-01, -2.20411794e-01, -1.45559685e-01,
       -1.40491226e-01, -2.57614879e-01, -2.94730581e-01, -2.69242694e-01,
       -2.20373944e-01, -1.57146788e-01, -2.29141933e-01,  2.63144288e-01,
       -2.98713536e-01, -2.43596631e-01, -2.78208652e-01,  4.55295782e-01,
       -2.76653590e-01, -1.91049695e-01, -2.16254073e-01, -2.41463076e-01,
        2.77665497e-01, -2.81639562e-01,  1.39400182e-01, -2.52434686e-01,
       -3.00738234e-01, -2.14165725e-01, -2.84662109e-01, -2.26010219e-01,
       -2.64260976e-01, -1.94625014e-01, -2.27023895e-01, -2.69479179e-01,
       -2.18119182e-01, -2.60938181e-01, -2.57683484e-01,  2.65274578e-01,
       -1.71574651e-01, -2.91851720e-01, -2.78728499e-01, -2.18405196e-01,
       -2.46944573e-01, -2.84229517e-01, -1.07296061e-01, -3.01124629e-01,
        1.58288701e+00, -2.67897683e-01, -2.74911543e-01, -2.69057709e-01,
       -2.87433456e-01, -2.34118872e-01,  1.05891007e+00, -2.95108537e-01,
       -2.74879488e-01,  3.71803617e-02, -2.91105030e-01, -6.48501481e-02,
       -2.82334695e-01, -3.01346777e-01, -1.80198525e-01, -2.63030124e-01,
       -2.28061991e-01, -1.46916064e-01, -2.40482013e-01, -2.41273107e-01,
       -2.99661163e-01, -1.81286415e-01, -1.12088210e-01, -1.98791172e-01,
        1.83163827e-02, -2.53848894e-01, -2.48008276e-01, -2.97642688e-01,
       -1.11137127e-01, -1.54838701e-01, -3.02108527e-01, -2.96396559e-01,
        9.64978016e-01,  2.60074862e-01, -2.19933236e-01, -2.80388970e-01,
       -2.55858371e-01, -2.99864287e-01, -2.47752507e-01, -2.62424340e-01,
       -1.74459533e-01,  5.78413292e-01, -2.65810745e-01, -1.11853796e-02,
       -2.64845785e-01, -2.88495471e-01,  3.55149781e-01, -2.91248779e-01,
        2.46553274e-01,  4.23174550e-01, -2.84835739e-01, -2.81255436e-01,
        3.31794464e-02, -2.67483444e-01, -2.08775055e-01, -2.99144164e-01,
       -2.55638854e-01, -2.78034837e-01, -2.67500368e-01, -2.13333597e-01,
        1.19439753e+00, -4.74514015e-03, -2.15925777e-01, -2.65665784e-01,
       -1.05135990e-01, -1.79847051e-01, -2.42393951e-01,  3.41687739e-01,
       -1.98943093e-01, -2.04806526e-01, -2.87688021e-01, -2.80470695e-01,
       -2.62458871e-01, -2.77790144e-01, -2.87781573e-01, -2.88379875e-01,
       -2.89584264e-01,  1.06610289e-01, -2.69925408e-01, -2.24531610e-01,
       -2.73507252e-01,  1.23066096e-01, -2.16625578e-01,  2.20162497e-02,
        2.24832622e-01, -2.85455381e-01, -2.40804003e-01, -2.72063436e-01,
       -5.24743705e-03, -8.37861651e-02,  7.19912374e-02, -2.64397291e-01,
       -2.65989217e-01, -2.74738299e-01, -1.90868861e-01, -2.14841152e-01,
       -7.39342225e-02, -2.45070757e-01, -2.97143337e-01, -2.83368549e-01,
       -2.60279637e-01, -2.90322134e-01, -2.60271251e-01, -4.12392231e-02,
       -1.94689662e-01,  2.19947665e-01, -1.35050462e-01, -2.38783739e-01,
       -1.98292991e-01, -2.43855411e-01, -2.64798460e-01, -1.26445427e-01,
       -2.65186032e-01, -3.00145280e-01, -1.87530149e-01, -2.68344618e-01,
       -2.79118135e-01, -2.71383300e-01,  6.15486207e-01,  6.99767263e-01,
       -2.81527267e-01, -2.49621030e-01, -2.10550150e-01,  5.56749802e-04,
       -2.88482500e-01, -1.90024259e-01,  2.03598695e+00,  5.16794455e-02,
       -1.97348321e-01, -2.90551960e-01,  3.33942098e-01, -2.46667761e-01,
       -2.25483888e-01, -5.04348557e-02,  9.77607727e-01,  1.70653435e-01,
       -2.97193752e-01, -2.54482174e-01, -2.42096846e-01, -2.61125317e-01,
       -1.39477247e-01, -1.35027721e-01, -1.25837980e-01, -1.84096520e-01,
       -1.80479774e-01, -2.97326363e-01, -2.71164512e-01, -1.33428806e-01,
       -2.13118738e-01, -2.20198952e-01, -2.53887528e-01, -2.92928799e-01,
       -2.02550586e-01, -2.12702640e-01, -1.00271869e-01, -1.66224342e-01,
        1.18999835e+00, -2.50130033e-01, -2.31831000e-01, -1.61267410e-01,
       -3.03166262e-01,  3.31355353e-02, -2.72544388e-01, -2.58771543e-01,
       -2.98555326e-01, -2.91880086e-01, -2.47163114e-01,  2.54341690e+00,
       -2.15382551e-01, -5.46487249e-02, -2.41542217e-01, -1.21747864e-01,
       -2.24416222e-01,  1.06049075e-01, -2.36428912e-01, -5.33953073e-02,
       -2.72375613e-01,  3.48013410e-01, -2.51584591e-01,  6.38111444e-02,
       -2.68663076e-01,  1.30620994e+00, -1.93840171e-01, -2.50687240e-01,
       -1.83752720e-01, -2.77822483e-01, -1.23512010e-01, -2.01802244e-01,
       -2.82340613e-01, -2.46091952e-01,  1.35030018e+00,  2.63996480e+00,
       -2.76860048e-01, -1.65932952e-01, -2.53069854e-01,  3.66737743e-01,
       -2.79325457e-01,  6.49634626e-03, -2.90195067e-01, -2.42118251e-01,
       -2.80528995e-01, -2.55107018e-01, -2.62405254e-01, -2.85300542e-01,
       -2.57846205e-01, -2.39054932e-01, -1.77097531e-01,  2.58126808e-01,
       -1.80671368e-01, -1.77064738e-01, -4.20439655e-02, -2.22665038e-01,
        1.11726231e+00, -2.64445641e-01, -2.32091481e-01, -1.57103634e-01,
       -2.89134578e-01, -2.77037536e-01, -1.57836419e-01, -2.34162649e-01,
       -5.20502378e-02, -2.20026706e-01, -2.44820798e-01,  8.94660175e-02,
       -2.31567056e-01, -2.87117065e-01, -2.60132394e-01, -2.27226526e-01,
       -2.97911363e-01, -2.20755182e-01, -1.46555136e-01, -1.96136116e-01,
       -1.40872667e-01, -2.87684541e-01, -2.76793605e-01, -2.89573343e-01,
        6.25484488e-01, -2.52193314e-01, -1.10391970e-01, -2.94015140e-01,
        2.74861228e-02, -1.46580872e-01,  1.82192167e-01,  8.43824964e-02,
       -2.68470782e-01, -2.41423075e-01, -2.28711442e-01,  1.64780720e+00,
       -2.06910867e-01, -2.66863628e-01,  1.73679027e+00, -2.41195559e-01,
       -3.01872239e-01,  1.15322093e+00,  6.10528053e-02, -2.69605254e-01,
       -2.58596877e-01, -1.43783743e-01, -2.45663926e-01, -3.14372884e-02,
       -7.28055554e-02, -2.20286269e-01, -2.32045871e-01, -1.95875929e-01,
       -2.37212472e-01, -2.00763411e-03, -2.16018861e-01, -1.25485253e-01,
       -1.27605648e-01, -9.63981148e-02,  1.18240613e-01, -2.91186215e-01,
       -1.94763804e-01, -2.71183850e-01, -3.03214259e-01, -2.40766532e-01,
        3.77296792e-01, -2.50612213e-01, -3.44269611e-02,  4.30138847e-01,
       -2.88879132e-01, -1.35612178e-01, -2.17043597e-01, -1.74231542e-01,
       -2.92406300e-01, -1.77048032e-01, -1.24348620e-01, -2.42104822e-01,
       -1.99397877e-01, -2.56890716e-01,  7.03046263e-01,  1.07942649e+00,
       -1.05354615e-01, -2.78833579e-01, -1.00460622e-01,  1.85656517e+00,
       -2.81177169e-01,  3.55665721e-01, -2.51631280e-01, -9.36872764e-02,
       -4.13484892e-02, -2.67366986e-01, -2.07686682e-01, -1.17541739e-01,
       -1.70420556e-01, -2.26536222e-01, -1.37220886e-01, -2.49524095e-01,
       -9.99978680e-02, -2.51720843e-01, -4.61535202e-04,  9.86786862e-01,
       -2.37138715e-01, -1.44276769e-01,  4.55064016e+00, -1.83807560e-01,
       -2.81889151e-01,  4.90650823e-02,  1.20923594e+00, -3.07372386e-02,
       -1.83504683e-01, -2.67319523e-01, -1.53285022e-01, -2.62080389e-01,
       -2.74391448e-01, -2.47567631e-01, -2.80754843e-01,  6.87909894e-01,
       -2.23381789e-01, -2.67493915e-01, -2.73742971e-01, -8.73764493e-02,
       -2.55400172e-01, -1.92215878e-01, -2.89422850e-01, -2.23880454e-01,
       -2.75660213e-01, -2.24657217e-01, -3.02557547e-01, -8.18235296e-02,
       -2.47138834e-01,  8.78195877e-02, -2.01304238e-02, -2.84441590e-01,
       -2.93991651e-01,  8.90452395e-01,  1.01788026e+00, -1.93760558e-01,
       -2.87663417e-01, -1.21263917e-01, -1.24950653e-01, -2.08578748e-01,
       -2.75136276e-01,  1.02512277e-01, -2.82435088e-01,  1.92963052e-01,
       -2.26596393e-01, -2.84564897e-01,  5.73021966e-01, -2.53563694e-01,
        5.00821106e-02, -5.88342110e-02, -3.03850875e-01, -2.11121295e-01,
        1.34678139e-01, -2.95503639e-01, -2.68064706e-01, -2.66057988e-01,
       -2.85327742e-01,  2.96540592e-01, -2.60424963e-01, -2.92565596e-01,
       -2.74043634e-01,  2.49073930e-01, -2.96381164e-01, -2.22884845e-01,
       -2.87109418e-01, -1.63905245e-01,  5.53986848e-02, -1.63905379e-01])

In [9]:
from sklearn.metrics import r2_score,root_mean_squared_error

r2 = r2_score(y_pred, y_test)
error2 = root_mean_squared_error(y_pred,y_test)

print(f'el r2 es {r2} y el error cuadratico medio es {error2}')

el r2 es 0.9796134361503718 y el error cuadratico medio es 0.07943780088361975

# ANALISIS

- El R2 de 0.97 es un muy buen modelo, aunque tambien podria indiqcar que hay variables correlacionadas con la objetivo
- El error cuadratico es bajo

# Visualizamos que variables sobrevivieron a Lasso

In [10]:
import pandas as pd
import matplotlib.pyplot as plt

# Crear un DataFrame con los nombres de las columnas y sus coeficientes
coeficientes = pd.DataFrame({
    'Variable': x_train.columns,
    'Coeficiente': lasso_model.coef_
})

# Filtrar solo las variables que el modelo NO eliminó (coeficiente != 0)
variables_seleccionadas = coeficientes[coeficientes['Coeficiente'] != 0].sort_values(by='Coeficiente', ascending=False)

print(f"Variables originales: {len(coeficientes)}")
print(f"Variables que dejó Lasso: {len(variables_seleccionadas)}")
print(variables_seleccionadas)

Variables originales: 107
Variables que dejó Lasso: 3
                  Variable  Coeficiente
86     anycondition_number     0.844722
2                      0-9     0.049148
70  Total Hospitals (2019)     0.017565

# CONCLUSION

- sobrevivio el 2% de las variables, lo que indica que la gran mayoria llego su pendiente a cero. (no tienen importancia para la variable objetivo)